covid_blog/urls.py
from django.urls import path

from . import views

app_name = "covid_blog"

urlpatterns = [
	path('', views.index, name='index'),

	path('<int:article_id>/', views.detail, name='details'),

	path('submit-article-form/', views.submit_article_form, name='submit_article'),

	path('success/', views.success, name='success'),

	path('image-upload/', views.upload_image, name='upload_image')
]

hello_django/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('covid-blog/', include('covid_blog.urls')),
    
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

covid_blog/models.py
from django.db import models

# class Author(models.Model):
# 	first_name = models.CharField(max_length=50)
# 	last_name = models.CharField(max_length=50)


class Article(models.Model):
	title = models.CharField(max_length=100)
	details = models.TextField()
	pub_date = models.DateTimeField('date published')
	#author = models.ForeignKey(Author, on_delete=models.CASCADE)


class Image(models.Model):
	title = models.CharField(max_length=200)
	image = models.ImageField(upload_to='images')

	def __str__(self):
		return self.title

covid_blog/forms.py
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ('title', 'image')

covid_blog/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

from .models import Article
from .forms import ImageForm

from django.core.mail import send_mail

def index(request):
	#return HttpResponse("Hello World! ")

	#latest_article_list = Article.objects.all()
	latest_article_list = Article.objects.order_by('-pub_date')

	template = loader.get_template('covid_blog/index.html')
	context = {
		'latest_article_list' : latest_article_list,
	}
	return HttpResponse(template.render(context,request))


def detail(request, article_id):
	
	#detailview = Article.objects.filter(id=article_id).values('details')
	detailview = Article.objects.get(id=article_id)
	#Article.objects.filter(id=1).values('details')

	template = loader.get_template('covid_blog/details.html')
	context = {
		'detailview' : detailview,
	}
	return HttpResponse(template.render(context,request))
	# print("HEERREE", article_id)
	# return HttpResponse("You are looking at article %s" % article_id)


def submit_article_form(request):
	return render(request,'covid_blog/submit_article.html', {})


def success(request):

	print(request.POST)
	try:

		article = Article(title=request.POST['title'], 
				details=request.POST['details'],
				pub_date=request.POST['pubdate'])
		article.save()

		if article.id is not None:
			template = loader.get_template('covid_blog/success.html')
			context = {

				"message" : "Success!",
				"article_id" : article.id
			}
			return HttpResponse(template.render(context, request))
		# else:
		# 	template = loader.get_template('covid_blog/success.html')
		# 	return HttpResponse(template.render({"message":"Error!!!"}, request))
	
	except Exception as error:
		template = loader.get_template('covid_blog/success.html')
		return HttpResponse(template.render({"message":"Error!!!"}, request))


def upload_image(request):

	if request.method == 'POST':
		image_form = ImageForm(request.POST, request.FILES)
		if image_form.is_valid():
			image_form.save()
			context = {
				"form": image_form,
				"img_obj": image_form.instance
			}
		return render(request,'covid_blog/image_upload.html', context)

	else:
		image_form = ImageForm()
		return render(request, 'covid_blog/image_upload.html', {'form': image_form} )


def send_mail_django(request):
	bool_value =  send_mail(
		'Subject here',
		'Here is the message',
		'bhaktimp02@gmail.com',
		['bhaktimp02@gmail.com'],
		fail_silently=False,
		)

	return HttpResponse("Mail success code: ", bool_value)

covid_blog/templates/covid_blog/details.html
{{ detailview.details}}
{{ detailview.title}}

covid_blog/templates/covid_blog/image_upload.html
<form method="post" enctype="multipart/form-data">
	{% csrf_token %}

	{{ form.as_p }}

	<button type="submit">Upload </button>	
</form>


{% if img_obj  %}
	<h3>Successfully Uploaded!!! : {img_obj.title}}</h3>
	<img src="{{ img_obj.image.url }}" alt="connect" style="max-height: 300px">
{% endif %}

covid_blog/templates/covid_blog/index.html
{% if latest_article_list %}
	<ul>
	{% for article in latest_article_list %}
		<li><a href="/covid-blog/{{ article.id }}/">{{article.title}}</a></li>
	{% endfor %}
	</ul>
{% endif %}

covid_blog/templates/covid_blog/submit_article.html
<h1> Add New Article </h1>

<form action = "{% url 'covid_blog:success' %}" method = "post">
{% csrf_token %}
	<!--Title-->

	<label for="title">Title:</label><br>
	<input type="text" name="title"> <br>

	<!--Article details-->
	<label for="details">Article Details:</label><br>
	<textarea name="details" rows="4" cols="50"></textarea><br>

	<!--Date Input-->
	<label for="pubdate">Published date:</label><br>
	<input type="date" name="pubdate" value="2021-02-18"><br>


	<!--Save Button-->
	<input type="submit" value="Save">

	
</form>

covid_blog/templates/covid_blog/success.html
{% if article_id  %}
	{{ message }}
{% else %}
	{{ message }}
{%  endif %}